In [1]:
# Convert the below list into numpy array then display tha array 
# input: my_list = [1,2,3,4,5]

import numpy as np

# input data
my_list = [1,2,3,4]

my_array = np.array(my_list)

# output
print(my_array)

[1 2 3 4]


In [2]:
# Convert the below list into a numpy array then display the array then display the first and last index and than multiply each element by 2 and 
# display the result 

import numpy as np

# input data
my_list = [1,2,3,4]

my_array = np.array(my_list)

print(my_array)

print("First element:", my_array[0])
print("Last element:", my_array[-1])

# Multiply each element by 2
multiplied_array = my_array * 2

print("updated array :",multiplied_array)


[1 2 3 4]
First element: 1
Last element: 4
updated array : [2 4 6 8]


In [3]:
# Write a numpy program to create an array of 10 zero,10 once,10 fives.

import numpy as np
arr = np.zeros((10)) 
# 10 zeros
print("Print 10 zeros in array :",arr)

arr = np.zeros((10)) +1
# 10 ones
print("Print 10 ones in array :",arr)

arr = np.zeros((10)) +5
# 10 five
print("Print 10 fives in array :",arr)

Print 10 zeros in array : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Print 10 ones in array : [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Print 10 fives in array : [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [4]:
# Write a numpy program to create a 3*3 matrix with values ranging from 2 to 10.

import numpy as np

matrix = np.arange(2, 11).reshape(3, 3)

# Print the matrix
print(matrix)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
